name: Test Against Regression
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: ensure correct user
        run: chown -R root /__w/cdktf-integration-serverless-example/
      - name: Install Dependencies
        run: yarn 
      - name: Generate Provider Bindings
        run: yarn get
      - name: Test
        run: yarn test
